CREATE DATABASE `TCC_CAP` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE TCC_CAP;
CREATE TABLE `CAP_CAPITAL_ACCOUNT` (
  `CAPITAL_ACCOUNT_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '账户编号',
  `BALANCE_AMOUNT` decimal(10,0) DEFAULT NULL COMMENT '账户余额',
  `USER_ID` int(11) DEFAULT NULL COMMENT '用户ID',
  PRIMARY KEY (`CAPITAL_ACCOUNT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='资金账户表';

CREATE TABLE `CAP_TRADE_ORDER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT  '交易订单ID',
  `SELF_USER_ID` bigint(11) DEFAULT NULL COMMENT '出款人',
  `OPPOSITE_USER_ID` bigint(11) DEFAULT NULL COMMENT '对方账户编号',
  `MERCHANT_ORDER_NO` varchar(45) NOT NULL COMMENT '商户订单号',
  `AMOUNT` decimal(10,0) DEFAULT NULL COMMENT '交易金额,单位(元)',
  `STATUS` varchar(45) DEFAULT NULL COMMENT '交易状态',
  `VERSION` int(11) DEFAULT NULL COMMENT '数据版本',
  PRIMARY KEY (`ID`) ,
  UNIQUE KEY `UX_MERCHANT_ORDER_NO` (`MERCHANT_ORDER_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='交易订单表';

INSERT INTO `CAP_CAPITAL_ACCOUNT`(CAPITAL_ACCOUNT_ID, BALANCE_AMOUNT, USER_ID) VALUE (1,10000,1000);
INSERT INTO `CAP_CAPITAL_ACCOUNT`(CAPITAL_ACCOUNT_ID, BALANCE_AMOUNT, USER_ID) VALUE (2,10000,2000);